# Generated by Django 3.2.5 on 2021-07-08 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210707_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
