# Generated by Django 3.2.5 on 2021-07-09 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210708_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_sales',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=1000),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_img_lg',
            field=models.ImageField(blank=True, upload_to='images-600'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_img_md',
            field=models.ImageField(blank=True, upload_to='images-300'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_img_sm',
            field=models.ImageField(blank=True, upload_to='images-150'),
        ),
    ]
